name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Compiling Java
      id: compiling-java
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Compiling Java
        setup-command: ''
        command: javac MatrixMultiplication.java
        timeout: 10
        max-score: 10
    - name: Checking column size consistency in CSV file
      id: checking-column-size-consistency-in-csv-file
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Checking column size consistency in CSV file
        setup-command: ''
        command: java MatrixMultiplication ./data/matrix3.csv ./data/matrix4.csv
        input: ''
        expected-output: Error! Column size is not the same in ./data/matrix4.csv
          at line 2
        comparison-method: contains
        timeout: 10
        max-score: 30
    - name: Matrix Multiplication 1
      id: matrix-multiplication-1
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Matrix Multiplication 1
        setup-command: ''
        command: java MatrixMultiplication ./data/matrix1.csv ./data/matrix2.csv
        input: ''
        expected-output: |-
          [[58.0,64.0],
          [139.0,154.0]]
        comparison-method: contains
        timeout: 10
        max-score: 30
    - name: Matrix Multiplication 2
      id: matrix-multiplication-2
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Matrix Multiplication 2
        setup-command: ''
        command: java MatrixMultiplication ./data/matrix5.csv ./data/matrix5.csv
        input: ''
        expected-output: |-
          [[310710.0,932115.0,554250.0],
          [158844.0,454551.0,265818.0],
          [408236.0,1198879.0,701328.0]]
        comparison-method: contains
        timeout: 10
        max-score: 30
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        COMPILING-JAVA_RESULTS: "${{steps.compiling-java.outputs.result}}"
        CHECKING-COLUMN-SIZE-CONSISTENCY-IN-CSV-FILE_RESULTS: "${{steps.checking-column-size-consistency-in-csv-file.outputs.result}}"
        MATRIX-MULTIPLICATION-1_RESULTS: "${{steps.matrix-multiplication-1.outputs.result}}"
        MATRIX-MULTIPLICATION-2_RESULTS: "${{steps.matrix-multiplication-2.outputs.result}}"
      with:
        runners: compiling-java,checking-column-size-consistency-in-csv-file,matrix-multiplication-1,matrix-multiplication-2
